# Generated by Django 5.2.17 on 2026-09-29 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_issue_ticca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='hourly_user_stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour_start', models.DateTimeField()),
                ('user_key', models.CharField(max_length=128)),
                ('requests', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hourly User Stat',
                'verbose_name_plural': 'Hourly User Stats',
                'db_table': 'issue_ticca_hourly_user_stat_x',
                'ordering': ['-hour_start'],
                'constraints': [models.UniqueConstraint(fields=('hour_start', 'user_key'), name='issue_ticca_hourly_unique')],
            },
        ),
    ]
